NUM_XYZ = 3
NUM_RPY = 3
NUM_QUAT = 4

POSITION_START_IDX, POSITION_END_IDX = 0, 3
QUAT_START_IDX, QUAT_END_IDX = 3, 7
LIN_VELOCITY_START_IDX, LIN_VELOCITY_END_IDX = 7, 10
ANG_VELOCITY_START_IDX, ANG_VELOCITY_END_IDX = 10, 13

ENV_REGEX_NS = "/World/envs/env_.*"
