from pathlib import Path

import fabrics_sim

fabrics_sim_path = Path(fabrics_sim.__file__).parent
URDF_PATH = (
    fabrics_sim_path
    / "models/robots/urdf/bimanual_kuka_allegro_v2/bimanual_kuka_allegro.urdf"
)
assert URDF_PATH.exists(), f"URDF file not found at {URDF_PATH}"

NUM_FINGERS = 4

RIGHT_PALM_LINK_NAME = "right_palm_link"
RIGHT_PALM_X_LINK_NAME = "right_palm_x"
RIGHT_PALM_Y_LINK_NAME = "right_palm_y"
RIGHT_PALM_Z_LINK_NAME = "right_palm_z"
RIGHT_PALM_LINK_NAMES = [
    RIGHT_PALM_LINK_NAME,
    RIGHT_PALM_X_LINK_NAME,
    RIGHT_PALM_Y_LINK_NAME,
    RIGHT_PALM_Z_LINK_NAME,
]

LEFT_PALM_LINK_NAME = "left_palm_link"
LEFT_PALM_X_LINK_NAME = "left_palm_x"
LEFT_PALM_Y_LINK_NAME = "left_palm_y"
LEFT_PALM_Z_LINK_NAME = "left_palm_z"
LEFT_PALM_LINK_NAMES = [
    LEFT_PALM_LINK_NAME,
    LEFT_PALM_X_LINK_NAME,
    LEFT_PALM_Y_LINK_NAME,
    LEFT_PALM_Z_LINK_NAME,
]

RIGHT_INDEX_FINGERTIP_LINK_NAME = "right_index_biotac_tip"
RIGHT_MIDDLE_FINGERTIP_LINK_NAME = "right_middle_biotac_tip"
RIGHT_RING_FINGERTIP_LINK_NAME = "right_ring_biotac_tip"
RIGHT_THUMB_FINGERTIP_LINK_NAME = "right_thumb_biotac_tip"
RIGHT_ALLEGRO_FINGERTIP_LINK_NAMES = [
    RIGHT_INDEX_FINGERTIP_LINK_NAME,
    RIGHT_MIDDLE_FINGERTIP_LINK_NAME,
    RIGHT_RING_FINGERTIP_LINK_NAME,
    RIGHT_THUMB_FINGERTIP_LINK_NAME,
]

LEFT_INDEX_FINGERTIP_LINK_NAME = "left_index_biotac_tip"
LEFT_MIDDLE_FINGERTIP_LINK_NAME = "left_middle_biotac_tip"
LEFT_RING_FINGERTIP_LINK_NAME = "left_ring_biotac_tip"
LEFT_THUMB_FINGERTIP_LINK_NAME = "left_thumb_biotac_tip"
LEFT_ALLEGRO_FINGERTIP_LINK_NAMES = [
    LEFT_INDEX_FINGERTIP_LINK_NAME,
    LEFT_MIDDLE_FINGERTIP_LINK_NAME,
    LEFT_RING_FINGERTIP_LINK_NAME,
    LEFT_THUMB_FINGERTIP_LINK_NAME,
]

assert len(RIGHT_ALLEGRO_FINGERTIP_LINK_NAMES) == NUM_FINGERS
assert len(LEFT_ALLEGRO_FINGERTIP_LINK_NAMES) == NUM_FINGERS

NUM_FABRIC_SPHERES = 38
NUM_FABRIC_WORLD_CUBES = 5

RIGHT_TASKMAP_LINK_NAMES = RIGHT_PALM_LINK_NAMES + RIGHT_ALLEGRO_FINGERTIP_LINK_NAMES
LEFT_TASKMAP_LINK_NAMES = LEFT_PALM_LINK_NAMES + LEFT_ALLEGRO_FINGERTIP_LINK_NAMES

RIGHT_PALM_LINK_IDX = RIGHT_TASKMAP_LINK_NAMES.index(RIGHT_PALM_LINK_NAME)
RIGHT_PALM_X_LINK_IDX = RIGHT_TASKMAP_LINK_NAMES.index(RIGHT_PALM_X_LINK_NAME)
RIGHT_PALM_Y_LINK_IDX = RIGHT_TASKMAP_LINK_NAMES.index(RIGHT_PALM_Y_LINK_NAME)
RIGHT_PALM_Z_LINK_IDX = RIGHT_TASKMAP_LINK_NAMES.index(RIGHT_PALM_Z_LINK_NAME)
LEFT_PALM_LINK_IDX = LEFT_TASKMAP_LINK_NAMES.index(LEFT_PALM_LINK_NAME)
LEFT_PALM_X_LINK_IDX = LEFT_TASKMAP_LINK_NAMES.index(LEFT_PALM_X_LINK_NAME)
LEFT_PALM_Y_LINK_IDX = LEFT_TASKMAP_LINK_NAMES.index(LEFT_PALM_Y_LINK_NAME)
LEFT_PALM_Z_LINK_IDX = LEFT_TASKMAP_LINK_NAMES.index(LEFT_PALM_Z_LINK_NAME)
RIGHT_INDEX_FINGERTIP_LINK_IDX = RIGHT_TASKMAP_LINK_NAMES.index(
    RIGHT_INDEX_FINGERTIP_LINK_NAME
)
RIGHT_MIDDLE_FINGERTIP_LINK_IDX = RIGHT_TASKMAP_LINK_NAMES.index(
    RIGHT_MIDDLE_FINGERTIP_LINK_NAME
)
RIGHT_RING_FINGERTIP_LINK_IDX = RIGHT_TASKMAP_LINK_NAMES.index(
    RIGHT_RING_FINGERTIP_LINK_NAME
)
RIGHT_THUMB_FINGERTIP_LINK_IDX = RIGHT_TASKMAP_LINK_NAMES.index(
    RIGHT_THUMB_FINGERTIP_LINK_NAME
)
LEFT_INDEX_FINGERTIP_LINK_IDX = LEFT_TASKMAP_LINK_NAMES.index(
    LEFT_INDEX_FINGERTIP_LINK_NAME
)
LEFT_MIDDLE_FINGERTIP_LINK_IDX = LEFT_TASKMAP_LINK_NAMES.index(
    LEFT_MIDDLE_FINGERTIP_LINK_NAME
)
LEFT_RING_FINGERTIP_LINK_IDX = LEFT_TASKMAP_LINK_NAMES.index(
    LEFT_RING_FINGERTIP_LINK_NAME
)
LEFT_THUMB_FINGERTIP_LINK_IDX = LEFT_TASKMAP_LINK_NAMES.index(
    LEFT_THUMB_FINGERTIP_LINK_NAME
)


USE_FABRIC_CUDA_GRAPH = False  # Leave this False almost all the time, CUDA graphs don't offer any speedup (actually slows down) with large batch size
